#!/usr/bin/env python3
"""FinAgent LLM Setup Wizard — configure your LLM API key interactively."""

import os
import sys
from pathlib import Path

try:
    import questionary
except ImportError:
    print("Installing questionary...")
    os.system(f"{sys.executable} -m pip install questionary -q")
    import questionary


PROVIDERS = {
    "deepseek": {
        "name": "DeepSeek",
        "subtitle": "Recommended — cheap, great quality, excellent for Chinese markets",
        "key_help": "Get your key at: https://platform.deepseek.com/",
        "env_vars": {"DEEPSEEK_API_KEY": "", "DEEPSEEK_BASE_URL": "https://api.deepseek.com"},
        "default_model": "deepseek-chat",
    },
    "dashscope": {
        "name": "Alibaba Tongyi (DashScope)",
        "subtitle": "Chinese provider — qwen models, stable access in China",
        "key_help": "Get your key at: https://dashscope.aliyun.com/",
        "env_vars": {"DASHSCOPE_API_KEY": ""},
        "default_model": "qwen-plus",
    },
    "openai": {
        "name": "OpenAI",
        "subtitle": "GPT-4o / GPT-4o-mini — powerful general-purpose models",
        "key_help": "Get your key at: https://platform.openai.com/api-keys",
        "env_vars": {"OPENAI_API_KEY": ""},
        "default_model": "gpt-4o-mini",
    },
    "google": {
        "name": "Google Gemini",
        "subtitle": "Gemini 2.5 Pro / Flash — strong free tier available",
        "key_help": "Get your key at: https://aistudio.google.com/apikey",
        "env_vars": {"GOOGLE_API_KEY": ""},
        "default_model": "gemini-2.0-flash",
    },
    "anthropic": {
        "name": "Anthropic Claude",
        "subtitle": "Claude Sonnet 4 — excellent reasoning and analysis",
        "key_help": "Get your key at: https://console.anthropic.com/",
        "env_vars": {"ANTHROPIC_API_KEY": ""},
        "default_model": "claude-sonnet-4-20250514",
    },
    "openrouter": {
        "name": "OpenRouter",
        "subtitle": "Multi-model aggregator — access 200+ models with one API key",
        "key_help": "Get your key at: https://openrouter.ai/keys",
        "env_vars": {"OPENROUTER_API_KEY": ""},
        "default_model": "openai/gpt-4o",
    },
    "siliconflow": {
        "name": "SiliconFlow",
        "subtitle": "Chinese provider — many open-source models, good pricing",
        "key_help": "Get your key at: https://www.siliconflow.cn/",
        "env_vars": {"SILICONFLOW_API_KEY": ""},
        "default_model": "deepseek-ai/DeepSeek-V3.2",
    },
    "ollama": {
        "name": "Local Ollama",
        "subtitle": "Free — run models locally, no API key or internet required",
        "key_help": "Install Ollama: https://ollama.com/",
        "env_vars": {
            "LLM_PROVIDER": "ollama",
            "OLLAMA_BASE_URL": "http://localhost:11434/v1",
            "DEFAULT_MODEL": "qwen2.5:7b",
        },
        "needs_key": False,
    },
    "custom": {
        "name": "Custom OpenAI-compatible endpoint",
        "subtitle": "Any service with an OpenAI-compatible API",
        "key_help": "",
        "env_vars": {"CUSTOM_OPENAI_API_KEY": "", "CUSTOM_OPENAI_BASE_URL": ""},
        "default_model": "",
    },
}


def load_existing_env(env_path: Path) -> dict[str, str]:
    """Load existing .env file into a dict, preserving comments and order."""
    existing = {}
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                existing[key.strip()] = value.strip()
    return existing


def write_env(env_path: Path, env_vars: dict[str, str]) -> None:
    """Write or update .env file with the given variables."""
    existing = load_existing_env(env_path)

    for key, value in env_vars.items():
        existing[key] = value

    lines = []
    lines.append("# FinAgent - Environment Configuration")
    lines.append(f"# Generated by setup_llm.py")
    lines.append("")
    lines.append("# ===== LLM Configuration =====")
    for key, value in existing.items():
        lines.append(f"{key}={value}")
    lines.append("")

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\n  Configuration saved to {env_path}")


def run_wizard():
    """Run the interactive LLM setup wizard."""
    print()
    print("  FinAgent - LLM Setup Wizard")
    print("  ==================================")
    print()

    # Build provider choices
    choices = []
    for key, info in PROVIDERS.items():
        title = f"{info['name']} — {info['subtitle']}"
        choices.append(questionary.Choice(title=title, value=key))

    provider_key = questionary.select(
        "Select your LLM provider:",
        choices=choices,
    ).ask()

    if provider_key is None:
        print("\n  Setup cancelled.")
        return

    provider = PROVIDERS[provider_key]
    env_vars = {}

    # Ask for API key (skip for ollama)
    if provider.get("needs_key", True):
        if provider_key == "custom":
            api_key = questionary.password(
                "Enter your API key:",
                validate=lambda text: True if text.strip() else "API key cannot be empty",
            ).ask()

            base_url = questionary.text(
                "Enter the base URL for your API endpoint:",
                default="https://your-api-endpoint.com/v1",
            ).ask()

            if api_key:
                env_vars["CUSTOM_OPENAI_API_KEY"] = api_key
            if base_url:
                env_vars["CUSTOM_OPENAI_BASE_URL"] = base_url
        else:
            help_text = provider["key_help"]
            api_key = questionary.password(
                f"Enter your {provider['name']} API key:\n  ({help_text})\n  Key:",
                validate=lambda text: True if text.strip() else "API key cannot be empty",
            ).ask()

            if api_key:
                # Set the appropriate env var
                for var_name in provider["env_vars"]:
                    env_vars[var_name] = api_key if not provider["env_vars"][var_name] else provider["env_vars"][var_name]
    else:
        # Ollama — no key needed, just set provider vars
        env_vars.update(provider["env_vars"])

    if not env_vars:
        print("\n  No configuration set. Setup cancelled.")
        return

    # Determine .env path (project root)
    project_root = Path(__file__).resolve().parent.parent
    env_path = project_root / ".env"

    write_env(env_path, env_vars)

    # Optional: configure data sources
    print()
    use_tushare = questionary.confirm(
        "Do you want to configure a Tushare token for A-share data? (AKShare is free and used by default)",
        default=False,
    ).ask()

    if use_tushare:
        token = questionary.password(
            "Enter your Tushare token:\n  (Get it at: https://tushare.pro/)",
        ).ask()
        if token:
            existing = load_existing_env(env_path)
            existing["TUSHARE_TOKEN"] = token
            env_path.write_text(
                "\n".join(f"{k}={v}" for k, v in existing.items()) + "\n",
                encoding="utf-8",
            )
            print(f"  Tushare token saved.")

    print()
    print("  " + "=" * 50)
    print("  Setup complete! Next steps:")
    print()
    print("    1. Install dependencies:")
    print("       pip install -e .")
    print()
    print("    2. Start FinAgent:")
    print("       python -m tradingagents")
    print()
    print("    3. Or use the CLI directly:")
    print("       cd tradingagents && python main.py")
    print("  " + "=" * 50)
    print()


if __name__ == "__main__":
    run_wizard()
