# tradingagents/core/contracts/__init__.py
"""
数据契约定义模块

定义所有 Agent 的数据契约，包括：
- 分析师契约 (analysts)
- 研究员契约 (researchers)
- 交易员和风控契约 (traders, risk_managers)
"""

from tradingagents.core.contracts.analysts import (
    MARKET_ANALYST_CONTRACT,
    NEWS_ANALYST_CONTRACT,
    SENTIMENT_ANALYST_CONTRACT,
    FUNDAMENTALS_ANALYST_CONTRACT,
    SECTOR_ANALYST_CONTRACT,
    INDEX_ANALYST_CONTRACT,
    ANALYST_CONTRACTS,
)
from tradingagents.core.contracts.researchers import (
    BULL_RESEARCHER_CONTRACT,
    BEAR_RESEARCHER_CONTRACT,
    RESEARCH_MANAGER_CONTRACT,
    RESEARCHER_CONTRACTS,
)
from tradingagents.core.contracts.traders import (
    TRADER_CONTRACT,
    RISKY_RISK_CONTRACT,
    SAFE_RISK_CONTRACT,
    NEUTRAL_RISK_CONTRACT,
    RISK_MANAGER_CONTRACT,
    TRADER_CONTRACTS,
)

# 所有契约汇总
ALL_CONTRACTS = {
    **ANALYST_CONTRACTS,
    **RESEARCHER_CONTRACTS,
    **TRADER_CONTRACTS,
}

__all__ = [
    # 分析师契约
    "MARKET_ANALYST_CONTRACT",
    "NEWS_ANALYST_CONTRACT",
    "SENTIMENT_ANALYST_CONTRACT",
    "FUNDAMENTALS_ANALYST_CONTRACT",
    "SECTOR_ANALYST_CONTRACT",
    "INDEX_ANALYST_CONTRACT",
    "ANALYST_CONTRACTS",
    # 研究员契约
    "BULL_RESEARCHER_CONTRACT",
    "BEAR_RESEARCHER_CONTRACT",
    "RESEARCH_MANAGER_CONTRACT",
    "RESEARCHER_CONTRACTS",
    # 交易员和风控契约
    "TRADER_CONTRACT",
    "RISKY_RISK_CONTRACT",
    "SAFE_RISK_CONTRACT",
    "NEUTRAL_RISK_CONTRACT",
    "RISK_MANAGER_CONTRACT",
    "TRADER_CONTRACTS",
    # 汇总
    "ALL_CONTRACTS",
]

